name: Challenge-CI

on:
  push:
    branches:
      - main
#    paths:
#      - 'website/**'
  workflow_dispatch:
    
jobs:     
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Unit Tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      run: |
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test

    - name: Static C0de Analysis
      uses: ioggstream/bandit-report-artifacts@v0.0.2
      with:
        project_path: .
        ignore_failure: true

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Security report
        path: output/security_report.txt
        
  build-and-push:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      env:
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        docker build -t $IMAGE_NAME:$GITHUB_SHA -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:$GITHUB_SHA
        docker push $IMAGE_NAME:latest
